name: CI

on: 
  pull_requests:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run build
      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist/